# 0. Install and Import Dependencies

In [8]:
!pip install tensorflow==2.4.1 tensorflow-gpu==2.4.1 opencv-python matplotlib

You should consider upgrading via the 'C:\Users\drago\PycharmProjects\bitcamp2022-v2\venv\Scripts\python.exe -m pip install --upgrade pip' command.


In [9]:
import tensorflow as tf
import numpy as np
from matplotlib import pyplot as plt
import cv2
import cvzone

# 1. Load Model

In [15]:
interpreter = tf.lite.Interpreter(model_path='lite-model_movenet_singlepose_lightning_3.tflite')
interpreter.allocate_tensors()

# 2. Make Detections

In [17]:
mask_path = "Drawing.sketchpad.png"
mask = cv2.imread(mask_path, cv2.IMREAD_UNCHANGED)


In [18]:
mask.shape
print(mask[50][102])


[254 186   0 255]


In [35]:
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    
    # Reshape image
    img = frame.copy()
    img = tf.image.resize_with_pad(np.expand_dims(img, axis=0), 192,192)
    input_image = tf.cast(img, dtype=tf.float32)
    print(frame.shape)
    # Setup input and output 
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    
    # Make predictions 
    interpreter.set_tensor(input_details[0]['index'], np.array(input_image))
    interpreter.invoke()
    keypoints_with_scores = interpreter.get_tensor(output_details[0]['index'])
    
    #resize and render mask

    frame = cv2.resize(frame, dsize=(843, 640), interpolation=cv2.INTER_CUBIC)
    mask = cv2.resize(mask, dsize=(843, 640), interpolation=cv2.INTER_CUBIC)
    
    #change dtype of mask
    mask = mask.astype('uint8')
    
    frame = np.concatenate((frame, np.full((640, 843, 1), 255, dtype = np.uint8)), axis=2)

    
    print(frame.shape)
    print(mask.shape)
    print(frame[:,:])
    frame = cv2.addWeighted(frame,1,mask,0.5,0)
    
    # Rendering 
    draw_connections(frame, keypoints_with_scores, EDGES, 0.4)
    draw_keypoints(frame, keypoints_with_scores, 0.4)
    
    
    cv2.imshow('MoveNet Lightning', frame)
    if cv2.waitKey(10) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[ 86  95  93 255]
  [ 86  95  93 255]
  [ 86  95  93 255]
  ...
  [232 217 197 255]
  [234 218 198 255]
  [235 219 199 255]]

 [[ 87  96  94 255]
  [ 87  96  94 255]
  [ 86  96  94 255]
  ...
  [177 163 146 255]
  [179 164 146 255]
  [179 164 146 255]]

 [[ 87  95  94 255]
  [ 87  95  94 255]
  [ 87  95  93 255]
  ...
  [127 114 102 255]
  [128 114 102 255]
  [127 114 102 255]]

 ...

 [[164 168 157 255]
  [164 168 157 255]
  [164 168 157 255]
  ...
  [ 81  70  45 255]
  [ 81  71  45 255]
  [ 81  71  46 255]]

 [[164 168 157 255]
  [164 168 157 255]
  [164 168 157 255]
  ...
  [ 81  71  45 255]
  [ 82  71  45 255]
  [ 83  72  46 255]]

 [[164 168 157 255]
  [164 168 157 255]
  [164 168 157 255]
  ...
  [ 82  71  44 255]
  [ 82  71  44 255]
  [ 83  72  45 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[ 88  91  90 255]
  [ 88  91  90 255]
  [ 89  91  90 255]
  ...
  [215 209 187 255]
  [214 208 185 255]
  [214 208 185 255]]

 [[ 88  91  90

(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[ 64  77  75 255]
  [ 64  76  74 255]
  [ 64  76  74 255]
  ...
  [193 178 156 255]
  [199 181 158 255]
  [201 183 160 255]]

 [[ 64  76  74 255]
  [ 64  76  73 255]
  [ 65  76  74 255]
  ...
  [160 145 125 255]
  [165 148 127 255]
  [168 149 129 255]]

 [[ 67  75  73 255]
  [ 66  75  73 255]
  [ 67  75  73 255]
  ...
  [110  96  84 255]
  [113  96  83 255]
  [114  96  83 255]]

 ...

 [[138 140 134 255]
  [139 141 135 255]
  [140 142 136 255]
  ...
  [ 82  64  43 255]
  [ 85  66  44 255]
  [ 86  67  44 255]]

 [[138 140 134 255]
  [138 140 134 255]
  [139 141 135 255]
  ...
  [ 83  64  40 255]
  [ 85  65  41 255]
  [ 86  65  40 255]]

 [[138 140 134 255]
  [139 141 135 255]
  [139 141 135 255]
  ...
  [ 84  64  40 255]
  [ 86  64  40 255]
  [ 86  64  39 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[ 58  74  75 255]
  [ 58  73  75 255]
  [ 60  73  75 255]
  ...
  [183 179 164 255]
  [179 175 160 255]
  [178 173 158 255]]

 [[ 59  73  74

(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[ 70  73  72 255]
  [ 69  72  71 255]
  [ 68  71  70 255]
  ...
  [186 173 158 255]
  [188 175 159 255]
  [188 176 159 255]]

 [[ 69  72  71 255]
  [ 67  71  70 255]
  [ 66  70  69 255]
  ...
  [131 118 105 255]
  [128 115 101 255]
  [125 114  99 255]]

 [[ 66  70  69 255]
  [ 64  69  68 255]
  [ 64  68  67 255]
  ...
  [ 93  83  73 255]
  [ 89  78  68 255]
  [ 85  74  64 255]]

 ...

 [[131 133 121 255]
  [130 133 121 255]
  [130 133 122 255]
  ...
  [ 94  93  86 255]
  [ 92  91  84 255]
  [ 91  90  84 255]]

 [[131 133 121 255]
  [130 133 121 255]
  [130 133 120 255]
  ...
  [ 95  92  85 255]
  [ 94  91  85 255]
  [ 93  90  84 255]]

 [[131 133 120 255]
  [130 133 120 255]
  [130 133 119 255]
  ...
  [ 95  92  85 255]
  [ 95  91  85 255]
  [ 94  90  85 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[ 59  67  67 255]
  [ 59  67  67 255]
  [ 59  67  67 255]
  ...
  [183 176 158 255]
  [186 180 162 255]
  [190 184 164 255]]

 [[ 58  66  66

(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[ 64  73  71 255]
  [ 65  74  72 255]
  [ 65  74  72 255]
  ...
  [195 178 176 255]
  [195 178 176 255]
  [194 177 175 255]]

 [[ 64  73  71 255]
  [ 64  73  71 255]
  [ 65  73  71 255]
  ...
  [133 118 116 255]
  [134 118 116 255]
  [134 118 116 255]]

 [[ 65  74  72 255]
  [ 65  74  72 255]
  [ 65  74  72 255]
  ...
  [ 93  81  80 255]
  [ 95  82  82 255]
  [ 96  83  82 255]]

 ...

 [[136 138 132 255]
  [136 138 132 255]
  [136 138 132 255]
  ...
  [ 94  98  96 255]
  [ 94  98  96 255]
  [ 94  98  97 255]]

 [[136 138 132 255]
  [136 138 132 255]
  [136 138 132 255]
  ...
  [ 94  98  96 255]
  [ 94  98  97 255]
  [ 94  98  97 255]]

 [[136 138 132 255]
  [136 138 132 255]
  [136 138 132 255]
  ...
  [ 94  98  97 255]
  [ 94  98  97 255]
  [ 94  98  97 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[ 72  72  72 255]
  [ 72  72  72 255]
  [ 72  72  72 255]
  ...
  [190 182 168 255]
  [192 183 168 255]
  [193 182 168 255]]

 [[ 74  73  73

(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[ 63  73  73 255]
  [ 62  72  72 255]
  [ 62  72  72 255]
  ...
  [191 184 174 255]
  [190 183 174 255]
  [189 182 173 255]]

 [[ 64  74  74 255]
  [ 64  73  74 255]
  [ 63  73  73 255]
  ...
  [152 145 137 255]
  [153 147 139 255]
  [154 147 139 255]]

 [[ 67  75  74 255]
  [ 66  75  74 255]
  [ 66  74  74 255]
  ...
  [103  96  92 255]
  [106  98  95 255]
  [107  99  96 255]]

 ...

 [[137 139 133 255]
  [137 139 133 255]
  [137 139 133 255]
  ...
  [ 95 100  93 255]
  [ 95 101  93 255]
  [ 96 101  93 255]]

 [[137 139 133 255]
  [137 139 133 255]
  [137 139 133 255]
  ...
  [ 93  99  91 255]
  [ 94 100  91 255]
  [ 94 101  92 255]]

 [[136 138 132 255]
  [137 139 133 255]
  [137 139 133 255]
  ...
  [ 92  98  90 255]
  [ 92  99  90 255]
  [ 93 100  90 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[ 74  73  75 255]
  [ 74  74  76 255]
  [ 73  75  76 255]
  ...
  [192 185 168 255]
  [193 185 168 255]
  [194 185 167 255]]

 [[ 75  75  77

(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[ 63  76  74 255]
  [ 63  76  74 255]
  [ 63  76  74 255]
  ...
  [186 179 155 255]
  [185 180 154 255]
  [184 180 154 255]]

 [[ 64  77  75 255]
  [ 64  76  74 255]
  [ 64  76  74 255]
  ...
  [143 136 115 255]
  [142 137 114 255]
  [143 137 115 255]]

 [[ 63  74  72 255]
  [ 63  75  73 255]
  [ 64  75  73 255]
  ...
  [ 98  91  77 255]
  [ 99  94  79 255]
  [101  95  80 255]]

 ...

 [[135 140 133 255]
  [135 140 133 255]
  [135 140 133 255]
  ...
  [100 102  97 255]
  [ 99 101  97 255]
  [ 99 101  96 255]]

 [[135 140 133 255]
  [135 140 133 255]
  [135 140 133 255]
  ...
  [ 98  99  94 255]
  [ 96  98  93 255]
  [ 96  98  93 255]]

 [[135 140 133 255]
  [135 140 133 255]
  [135 140 133 255]
  ...
  [ 93  95  90 255]
  [ 92  94  89 255]
  [ 91  93  88 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[ 72  75  76 255]
  [ 71  75  76 255]
  [ 69  75  76 255]
  ...
  [180 180 167 255]
  [181 181 167 255]
  [180 180 167 255]]

 [[ 74  76  78

# 3. Draw Keypoints

In [11]:
def draw_keypoints(frame, keypoints, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for kp in shaped:
        ky, kx, kp_conf = kp
        if kp_conf > confidence_threshold:
            cv2.circle(frame, (int(kx), int(ky)), 4, (0,255,0), -1) 

# 4. Draw Edges

In [12]:
EDGES = {
    (0, 1): 'm',
    (0, 2): 'c',
    (1, 3): 'm',
    (2, 4): 'c',
    (0, 5): 'm',
    (0, 6): 'c',
    (5, 7): 'm',
    (7, 9): 'm',
    (6, 8): 'c',
    (8, 10): 'c',
    (5, 6): 'y',
    (5, 11): 'm',
    (6, 12): 'c',
    (11, 12): 'y',
    (11, 13): 'm',
    (13, 15): 'm',
    (12, 14): 'c',
    (14, 16): 'c'
}

In [13]:
def draw_connections(frame, keypoints, edges, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for edge, color in edges.items():
        p1, p2 = edge
        y1, x1, c1 = shaped[p1]
        y2, x2, c2 = shaped[p2]
        
        if (c1 > confidence_threshold) & (c2 > confidence_threshold):      
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0,0,255), 2)

In [14]:
mask.shape

NameError: name 'mask' is not defined