# 0. Install and Import Dependencies

In [8]:
!pip install tensorflow==2.4.1 tensorflow-gpu==2.4.1 opencv-python matplotlib

You should consider upgrading via the 'C:\Users\drago\PycharmProjects\bitcamp2022-v2\venv\Scripts\python.exe -m pip install --upgrade pip' command.


In [9]:
import tensorflow as tf
import numpy as np
from matplotlib import pyplot as plt
import cv2
import cvzone

# 1. Load Model

In [15]:
interpreter = tf.lite.Interpreter(model_path='lite-model_movenet_singlepose_lightning_3.tflite')
interpreter.allocate_tensors()

# 2. Make Detections

In [17]:
mask_path = "Drawing.sketchpad.png"
mask = cv2.imread(mask_path, cv2.IMREAD_UNCHANGED)


In [18]:
mask.shape
print(mask[50][102])


[254 186   0 255]


In [34]:
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    
    # Reshape image
    img = frame.copy()
    img = tf.image.resize_with_pad(np.expand_dims(img, axis=0), 192,192)
    input_image = tf.cast(img, dtype=tf.float32)
    print(frame.shape)
    # Setup input and output 
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    
    # Make predictions 
    interpreter.set_tensor(input_details[0]['index'], np.array(input_image))
    interpreter.invoke()
    keypoints_with_scores = interpreter.get_tensor(output_details[0]['index'])
    
    #resize and render mask

    frame = cv2.resize(frame, dsize=(843, 640), interpolation=cv2.INTER_CUBIC)
    mask = cv2.resize(mask, dsize=(843, 640), interpolation=cv2.INTER_CUBIC)
    
    #change dtype of mask
    mask = mask.astype('uint8')
    
    frame = np.concatenate((frame, np.full((640, 843, 1), 255, dtype = np.uint8)), axis=2)

    
    print(frame.shape)
    print(mask.shape)
    print(frame[:,:])
    frame = cv2.addWeighted(frame,1,mask,0.5,0)
    
    # Rendering 
    draw_connections(frame, keypoints_with_scores, EDGES, 0.4)
    draw_keypoints(frame, keypoints_with_scores, 0.4)
    
    
    cv2.imshow('MoveNet Lightning', frame)
    if cv2.waitKey(10) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[193 195 176 255]
  [193 195 176 255]
  [193 195 176 255]
  ...
  [140 143 134 255]
  [140 143 134 255]
  [139 142 133 255]]

 [[193 195 176 255]
  [193 195 176 255]
  [193 195 176 255]
  ...
  [140 143 134 255]
  [140 143 134 255]
  [139 142 133 255]]

 [[193 195 176 255]
  [193 195 176 255]
  [194 196 177 255]
  ...
  [140 143 134 255]
  [140 143 134 255]
  [139 142 133 255]]

 ...

 [[ 35  43  45 255]
  [ 35  43  46 255]
  [ 35  44  46 255]
  ...
  [ 92 102 129 255]
  [ 92 102 129 255]
  [ 92 102 129 255]]

 [[ 34  45  47 255]
  [ 34  46  47 255]
  [ 34  46  48 255]
  ...
  [ 90 102 127 255]
  [ 90 102 127 255]
  [ 90 102 127 255]]

 [[ 34  46  48 255]
  [ 34  46  48 255]
  [ 33  46  48 255]
  ...
  [ 89 101 127 255]
  [ 89 101 127 255]
  [ 89 101 127 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[193 197 180 255]
  [193 197 180 255]
  [193 197 180 255]
  ...
  [141 144 135 255]
  [141 144 135 255]
  [142 145 136 255]]

 [[193 196 179

(640, 843, 4)
(640, 843, 4)
[[[190 192 179 255]
  [190 192 179 255]
  [190 192 179 255]
  ...
  [144 146 140 255]
  [144 146 140 255]
  [144 146 140 255]]

 [[189 192 179 255]
  [190 192 179 255]
  [190 193 180 255]
  ...
  [144 146 141 255]
  [144 146 140 255]
  [144 146 140 255]]

 [[189 193 179 255]
  [190 193 180 255]
  [190 194 180 255]
  ...
  [144 146 140 255]
  [144 146 140 255]
  [144 146 140 255]]

 ...

 [[ 36  42  52 255]
  [ 36  42  53 255]
  [ 36  42  52 255]
  ...
  [ 48  44  36 255]
  [ 50  45  37 255]
  [ 52  47  39 255]]

 [[ 36  45  57 255]
  [ 36  45  57 255]
  [ 37  45  57 255]
  ...
  [ 45  42  34 255]
  [ 47  43  35 255]
  [ 49  45  37 255]]

 [[ 36  46  58 255]
  [ 36  46  58 255]
  [ 36  46  58 255]
  ...
  [ 44  41  33 255]
  [ 46  43  35 255]
  [ 47  44  36 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[197 191 172 255]
  [197 191 172 255]
  [197 191 172 255]
  ...
  [143 145 138 255]
  [143 146 138 255]
  [143 146 137 255]]

 [[197 191 172 255]
  [197 1

(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[177 181 162 255]
  [177 182 163 255]
  [178 182 163 255]
  ...
  [131 134 133 255]
  [131 134 131 255]
  [130 133 130 255]]

 [[177 182 163 255]
  [178 182 163 255]
  [180 183 164 255]
  ...
  [131 134 132 255]
  [130 133 130 255]
  [130 134 130 255]]

 [[179 184 163 255]
  [180 184 163 255]
  [181 184 164 255]
  ...
  [130 134 130 255]
  [130 133 129 255]
  [130 134 129 255]]

 ...

 [[ 30  35  37 255]
  [ 30  35  37 255]
  [ 30  35  36 255]
  ...
  [ 51  49  39 255]
  [ 48  46  37 255]
  [ 46  44  35 255]]

 [[ 32  35  38 255]
  [ 32  35  38 255]
  [ 32  35  38 255]
  ...
  [ 52  49  41 255]
  [ 49  46  38 255]
  [ 47  44  36 255]]

 [[ 33  35  39 255]
  [ 33  35  39 255]
  [ 33  35  39 255]
  ...
  [ 53  50  41 255]
  [ 49  46  38 255]
  [ 47  44  36 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[185 183 165 255]
  [185 183 165 255]
  [185 183 165 255]
  ...
  [132 138 122 255]
  [132 139 122 255]
  [131 139 122 255]]

 [[184 183 166

(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[190 184 159 255]
  [190 184 159 255]
  [188 184 159 255]
  ...
  [132 135 127 255]
  [132 135 127 255]
  [132 135 126 255]]

 [[190 184 159 255]
  [189 184 159 255]
  [187 184 159 255]
  ...
  [132 135 128 255]
  [133 136 127 255]
  [133 136 126 255]]

 [[189 184 159 255]
  [188 184 159 255]
  [187 184 159 255]
  ...
  [133 135 128 255]
  [133 136 128 255]
  [133 136 127 255]]

 ...

 [[ 30  35  42 255]
  [ 31  35  42 255]
  [ 31  34  42 255]
  ...
  [ 38  32  27 255]
  [ 38  32  27 255]
  [ 38  32  27 255]]

 [[ 30  34  42 255]
  [ 30  33  42 255]
  [ 31  34  42 255]
  ...
  [ 38  32  27 255]
  [ 38  32  27 255]
  [ 38  32  27 255]]

 [[ 30  33  41 255]
  [ 30  33  41 255]
  [ 31  33  41 255]
  ...
  [ 38  32  27 255]
  [ 38  32  27 255]
  [ 38  32  27 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[183 186 161 255]
  [184 187 162 255]
  [184 187 162 255]
  ...
  [136 138 126 255]
  [136 138 126 255]
  [136 138 126 255]]

 [[184 187 161

(640, 843, 4)
(640, 843, 4)
[[[191 186 158 255]
  [190 185 157 255]
  [190 185 157 255]
  ...
  [133 135 126 255]
  [133 135 126 255]
  [132 135 126 255]]

 [[190 186 158 255]
  [190 186 158 255]
  [190 186 158 255]
  ...
  [133 135 127 255]
  [133 136 126 255]
  [133 136 127 255]]

 [[190 186 158 255]
  [190 186 158 255]
  [190 186 159 255]
  ...
  [133 136 128 255]
  [133 137 128 255]
  [133 136 127 255]]

 ...

 [[ 29  33  45 255]
  [ 29  33  45 255]
  [ 29  33  45 255]
  ...
  [ 30  36  31 255]
  [ 27  34  29 255]
  [ 26  34  29 255]]

 [[ 31  35  47 255]
  [ 31  35  47 255]
  [ 31  34  47 255]
  ...
  [ 28  36  31 255]
  [ 26  34  31 255]
  [ 26  34  31 255]]

 [[ 32  36  49 255]
  [ 32  35  49 255]
  [ 32  35  49 255]
  ...
  [ 26  36  31 255]
  [ 26  35  31 255]
  [ 26  35  32 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[179 184 163 255]
  [179 184 163 255]
  [179 184 163 255]
  ...
  [134 140 124 255]
  [135 141 124 255]
  [135 141 124 255]]

 [[179 184 163 255]
  [179 1

(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[182 184 165 255]
  [182 184 165 255]
  [182 184 165 255]
  ...
  [133 136 128 255]
  [133 136 128 255]
  [133 136 127 255]]

 [[182 184 165 255]
  [182 184 165 255]
  [183 185 166 255]
  ...
  [133 136 128 255]
  [134 137 128 255]
  [134 137 128 255]]

 [[182 184 165 255]
  [183 185 166 255]
  [183 185 166 255]
  ...
  [134 137 128 255]
  [134 138 128 255]
  [134 137 127 255]]

 ...

 [[ 30  38  46 255]
  [ 30  38  46 255]
  [ 30  38  45 255]
  ...
  [ 41  42  37 255]
  [ 37  39  34 255]
  [ 34  36  31 255]]

 [[ 33  39  46 255]
  [ 33  40  46 255]
  [ 33  40  46 255]
  ...
  [ 41  42  37 255]
  [ 39  41  36 255]
  [ 38  40  35 255]]

 [[ 33  39  46 255]
  [ 34  40  47 255]
  [ 34  40  47 255]
  ...
  [ 41  42  37 255]
  [ 41  42  37 255]
  [ 40  42  37 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[186 182 171 255]
  [186 182 171 255]
  [186 182 171 255]
  ...
  [134 135 126 255]
  [134 135 126 255]
  [135 136 127 255]]

 [[185 182 170

(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[184 185 166 255]
  [184 185 166 255]
  [184 185 166 255]
  ...
  [130 130 128 255]
  [130 130 126 255]
  [130 129 125 255]]

 [[184 184 165 255]
  [184 185 166 255]
  [184 185 166 255]
  ...
  [131 131 128 255]
  [130 130 127 255]
  [130 130 126 255]]

 [[185 183 165 255]
  [185 184 166 255]
  [186 185 166 255]
  ...
  [131 132 129 255]
  [132 132 128 255]
  [132 132 128 255]]

 ...

 [[ 30  35  44 255]
  [ 30  35  44 255]
  [ 29  34  43 255]
  ...
  [ 31  33  32 255]
  [ 30  32  31 255]
  [ 28  31  30 255]]

 [[ 32  37  46 255]
  [ 31  36  45 255]
  [ 31  36  45 255]
  ...
  [ 32  33  31 255]
  [ 30  32  30 255]
  [ 29  31  29 255]]

 [[ 33  38  47 255]
  [ 33  38  47 255]
  [ 33  38  47 255]
  ...
  [ 31  32  30 255]
  [ 31  31  29 255]
  [ 30  31  29 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[187 182 167 255]
  [187 182 167 255]
  [187 182 167 255]
  ...
  [134 135 131 255]
  [134 135 131 255]
  [134 136 131 255]]

 [[187 182 167

(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[187 181 170 255]
  [188 181 171 255]
  [189 183 172 255]
  ...
  [135 135 128 255]
  [137 135 128 255]
  [138 136 128 255]]

 [[187 182 171 255]
  [188 182 171 255]
  [189 183 171 255]
  ...
  [135 134 127 255]
  [136 135 127 255]
  [137 136 128 255]]

 [[186 182 171 255]
  [187 183 171 255]
  [187 183 171 255]
  ...
  [135 135 126 255]
  [135 136 126 255]
  [135 136 126 255]]

 ...

 [[ 35  35  45 255]
  [ 33  33  44 255]
  [ 32  32  42 255]
  ...
  [ 40  37  33 255]
  [ 42  38  34 255]
  [ 42  39  35 255]]

 [[ 36  36  47 255]
  [ 34  34  45 255]
  [ 33  33  44 255]
  ...
  [ 40  36  32 255]
  [ 41  37  33 255]
  [ 42  38  34 255]]

 [[ 36  36  47 255]
  [ 35  35  46 255]
  [ 34  34  45 255]
  ...
  [ 39  35  31 255]
  [ 40  36  32 255]
  [ 41  37  33 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[174 180 157 255]
  [176 182 159 255]
  [180 185 163 255]
  ...
  [130 138 125 255]
  [130 138 125 255]
  [131 139 126 255]]

 [[174 179 157

(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[182 183 167 255]
  [182 183 167 255]
  [182 183 167 255]
  ...
  [132 134 128 255]
  [132 134 128 255]
  [132 134 128 255]]

 [[183 185 168 255]
  [183 185 168 255]
  [183 185 168 255]
  ...
  [133 135 128 255]
  [133 135 128 255]
  [133 135 127 255]]

 [[185 186 168 255]
  [185 186 168 255]
  [185 187 168 255]
  ...
  [134 137 127 255]
  [135 137 127 255]
  [135 137 127 255]]

 ...

 [[ 31  36  40 255]
  [ 32  36  41 255]
  [ 33  36  44 255]
  ...
  [ 37  39  34 255]
  [ 33  36  31 255]
  [ 31  35  30 255]]

 [[ 35  38  40 255]
  [ 35  38  41 255]
  [ 36  39  43 255]
  ...
  [ 36  41  34 255]
  [ 32  38  31 255]
  [ 31  37  30 255]]

 [[ 37  40  41 255]
  [ 37  40  41 255]
  [ 38  40  43 255]
  ...
  [ 36  42  35 255]
  [ 32  39  32 255]
  [ 31  37  30 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[186 181 166 255]
  [187 182 167 255]
  [187 182 167 255]
  ...
  [132 136 132 255]
  [132 137 132 255]
  [132 137 132 255]]

 [[187 182 167

(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[181 182 172 255]
  [181 183 173 255]
  [182 185 174 255]
  ...
  [132 135 134 255]
  [130 135 134 255]
  [129 135 134 255]]

 [[180 182 171 255]
  [181 183 171 255]
  [181 184 172 255]
  ...
  [132 135 134 255]
  [130 136 135 255]
  [130 136 135 255]]

 [[180 182 169 255]
  [181 183 170 255]
  [181 183 170 255]
  ...
  [132 135 135 255]
  [130 136 135 255]
  [130 136 135 255]]

 ...

 [[ 31  37  45 255]
  [ 32  37  45 255]
  [ 33  38  45 255]
  ...
  [ 22  22  22 255]
  [ 22  22  22 255]
  [ 22  22  22 255]]

 [[ 32  38  45 255]
  [ 33  39  46 255]
  [ 34  39  47 255]
  ...
  [ 21  21  21 255]
  [ 22  22  22 255]
  [ 22  22  22 255]]

 [[ 32  38  45 255]
  [ 32  39  46 255]
  [ 34  39  46 255]
  ...
  [ 21  21  21 255]
  [ 21  21  21 255]
  [ 21  21  21 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[184 184 161 255]
  [184 184 161 255]
  [184 184 161 255]
  ...
  [130 132 133 255]
  [130 132 133 255]
  [130 132 133 255]]

 [[185 185 162

(640, 843, 4)
(640, 843, 4)
[[[185 183 167 255]
  [184 182 166 255]
  [183 182 166 255]
  ...
  [135 138 128 255]
  [135 139 128 255]
  [135 139 128 255]]

 [[185 183 166 255]
  [185 183 166 255]
  [185 182 166 255]
  ...
  [135 138 128 255]
  [135 139 128 255]
  [135 139 128 255]]

 [[187 183 164 255]
  [187 183 164 255]
  [186 183 164 255]
  ...
  [134 138 128 255]
  [135 139 128 255]
  [135 139 128 255]]

 ...

 [[ 22  37  44 255]
  [ 22  37  44 255]
  [ 22  37  44 255]
  ...
  [ 35  34  32 255]
  [ 35  34  32 255]
  [ 35  34  32 255]]

 [[ 25  39  45 255]
  [ 25  39  45 255]
  [ 24  39  44 255]
  ...
  [ 35  34  32 255]
  [ 35  34  32 255]
  [ 35  34  32 255]]

 [[ 27  41  47 255]
  [ 27  41  47 255]
  [ 25  39  45 255]
  ...
  [ 35  34  32 255]
  [ 35  34  32 255]
  [ 35  34  32 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[188 184 160 255]
  [187 183 159 255]
  [187 182 159 255]
  ...
  [130 135 128 255]
  [132 137 128 255]
  [132 137 128 255]]

 [[188 184 160 255]
  [188 1

(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[179 179 166 255]
  [179 179 166 255]
  [179 179 166 255]
  ...
  [134 138 136 255]
  [134 138 138 255]
  [135 139 138 255]]

 [[179 179 166 255]
  [179 179 166 255]
  [179 179 166 255]
  ...
  [133 138 136 255]
  [134 138 138 255]
  [135 139 138 255]]

 [[179 179 166 255]
  [179 179 166 255]
  [179 179 166 255]
  ...
  [134 138 136 255]
  [135 138 138 255]
  [135 139 138 255]]

 ...

 [[ 45  53  74 255]
  [ 46  53  74 255]
  [ 46  53  73 255]
  ...
  [ 47  46  35 255]
  [ 47  46  36 255]
  [ 47  46  36 255]]

 [[ 49  54  73 255]
  [ 49  53  73 255]
  [ 48  52  72 255]
  ...
  [ 45  44  34 255]
  [ 45  44  34 255]
  [ 45  44  35 255]]

 [[ 52  56  75 255]
  [ 52  55  74 255]
  [ 51  53  72 255]
  ...
  [ 43  42  32 255]
  [ 44  43  33 255]
  [ 45  44  34 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[175 176 167 255]
  [174 175 166 255]
  [172 173 164 255]
  ...
  [132 137 133 255]
  [132 137 133 255]
  [132 137 133 255]]

 [[175 176 166

(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[152 152 132 255]
  [153 151 132 255]
  [154 150 133 255]
  ...
  [141 144 142 255]
  [141 144 142 255]
  [141 144 142 255]]

 [[127 126 106 255]
  [128 125 106 255]
  [128 124 106 255]
  ...
  [141 144 142 255]
  [141 143 141 255]
  [141 143 141 255]]

 [[115 110  90 255]
  [115 110  91 255]
  [115 108  91 255]
  ...
  [142 143 141 255]
  [142 143 141 255]
  [142 143 141 255]]

 ...

 [[ 24  34  52 255]
  [ 24  34  52 255]
  [ 24  34  52 255]
  ...
  [ 44  46  52 255]
  [ 42  44  52 255]
  [ 41  44  51 255]]

 [[ 24  34  52 255]
  [ 24  34  52 255]
  [ 24  34  52 255]
  ...
  [ 43  46  52 255]
  [ 42  44  52 255]
  [ 41  44  51 255]]

 [[ 24  34  52 255]
  [ 24  34  52 255]
  [ 24  34  52 255]
  ...
  [ 43  46  52 255]
  [ 41  44  52 255]
  [ 41  44  51 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[173 174 155 255]
  [172 174 154 255]
  [172 173 154 255]
  ...
  [150 152 147 255]
  [150 152 147 255]
  [150 152 147 255]]

 [[173 172 155

(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[179 183 172 255]
  [179 183 172 255]
  [179 183 172 255]
  ...
  [ 62  68  68 255]
  [ 60  66  66 255]
  [ 59  64  65 255]]

 [[179 182 171 255]
  [179 182 171 255]
  [179 183 172 255]
  ...
  [ 63  68  68 255]
  [ 61  66  67 255]
  [ 61  66  66 255]]

 [[179 182 171 255]
  [179 182 170 255]
  [179 182 171 255]
  ...
  [ 65  68  69 255]
  [ 64  67  68 255]
  [ 63  68  67 255]]

 ...

 [[ 61  72  94 255]
  [ 60  72  93 255]
  [ 59  71  92 255]
  ...
  [ 33  31  25 255]
  [ 34  31  26 255]
  [ 34  32  27 255]]

 [[ 53  66  89 255]
  [ 53  65  88 255]
  [ 52  65  87 255]
  ...
  [ 33  31  25 255]
  [ 33  31  25 255]
  [ 34  32  26 255]]

 [[ 45  57  81 255]
  [ 45  58  81 255]
  [ 45  58  81 255]
  ...
  [ 33  31  25 255]
  [ 33  31  25 255]
  [ 33  31  25 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[174 179 164 255]
  [173 178 163 255]
  [173 178 163 255]
  ...
  [ 72  78  78 255]
  [ 68  74  74 255]
  [ 67  73  73 255]]

 [[174 179 164

(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[182 185 170 255]
  [182 185 170 255]
  [182 185 170 255]
  ...
  [ 65  64  66 255]
  [ 65  64  66 255]
  [ 65  64  66 255]]

 [[182 185 170 255]
  [182 185 170 255]
  [182 185 170 255]
  ...
  [ 68  67  69 255]
  [ 67  66  68 255]
  [ 66  66  67 255]]

 [[182 185 170 255]
  [182 185 170 255]
  [182 185 170 255]
  ...
  [ 69  69  70 255]
  [ 67  68  69 255]
  [ 66  67  68 255]]

 ...

 [[ 27  36  46 255]
  [ 26  36  45 255]
  [ 26  35  44 255]
  ...
  [ 44  40  32 255]
  [ 44  40  32 255]
  [ 44  40  32 255]]

 [[ 25  36  46 255]
  [ 25  37  46 255]
  [ 25  36  45 255]
  ...
  [ 42  40  32 255]
  [ 42  40  32 255]
  [ 42  40  32 255]]

 [[ 24  37  46 255]
  [ 24  37  46 255]
  [ 25  37  45 255]
  ...
  [ 41  39  31 255]
  [ 41  39  31 255]
  [ 42  40  32 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[180 185 170 255]
  [182 186 171 255]
  [182 186 171 255]
  ...
  [ 59  67  74 255]
  [ 57  65  72 255]
  [ 54  63  70 255]]

 [[179 184 169

(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[182 182 176 255]
  [181 181 175 255]
  [181 181 175 255]
  ...
  [ 61  66  65 255]
  [ 59  64  63 255]
  [ 58  62  61 255]]

 [[181 181 175 255]
  [181 181 174 255]
  [181 181 174 255]
  ...
  [ 62  66  65 255]
  [ 59  64  63 255]
  [ 58  62  61 255]]

 [[181 181 174 255]
  [181 181 174 255]
  [181 181 174 255]
  ...
  [ 63  67  66 255]
  [ 61  65  64 255]
  [ 60  64  63 255]]

 ...

 [[ 32  38  39 255]
  [ 32  38  39 255]
  [ 31  38  40 255]
  ...
  [ 30  29  27 255]
  [ 30  29  27 255]
  [ 30  29  27 255]]

 [[ 34  38  39 255]
  [ 34  38  40 255]
  [ 33  38  40 255]
  ...
  [ 30  29  27 255]
  [ 30  29  27 255]
  [ 30  29  27 255]]

 [[ 35  38  39 255]
  [ 35  38  40 255]
  [ 34  38  40 255]
  ...
  [ 30  29  27 255]
  [ 30  29  27 255]
  [ 30  29  27 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[176 178 165 255]
  [177 179 166 255]
  [180 182 170 255]
  ...
  [ 57  73  76 255]
  [ 55  71  74 255]
  [ 53  70  73 255]]

 [[178 180 167

(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[176 183 170 255]
  [176 184 171 255]
  [177 184 171 255]
  ...
  [ 59  68  72 255]
  [ 55  66  70 255]
  [ 54  65  69 255]]

 [[178 184 171 255]
  [178 185 172 255]
  [178 185 172 255]
  ...
  [ 60  68  73 255]
  [ 56  67  70 255]
  [ 55  65  69 255]]

 [[180 185 172 255]
  [180 185 172 255]
  [180 185 172 255]
  ...
  [ 62  69  74 255]
  [ 59  68  71 255]
  [ 57  66  70 255]]

 ...

 [[ 34  36  37 255]
  [ 34  36  37 255]
  [ 34  37  38 255]
  ...
  [ 31  30  28 255]
  [ 31  30  28 255]
  [ 31  30  28 255]]

 [[ 37  36  36 255]
  [ 38  37  37 255]
  [ 36  37  38 255]
  ...
  [ 31  30  28 255]
  [ 31  30  28 255]
  [ 31  30  28 255]]

 [[ 38  36  36 255]
  [ 38  37  37 255]
  [ 37  37  38 255]
  ...
  [ 31  30  28 255]
  [ 31  30  28 255]
  [ 31  30  28 255]]]
(480, 640, 3)
(640, 843, 4)
(640, 843, 4)
[[[177 183 172 255]
  [178 184 173 255]
  [180 185 174 255]
  ...
  [ 64  70  77 255]
  [ 62  68  75 255]
  [ 61  67  74 255]]

 [[177 183 171

# 3. Draw Keypoints

In [11]:
def draw_keypoints(frame, keypoints, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for kp in shaped:
        ky, kx, kp_conf = kp
        if kp_conf > confidence_threshold:
            cv2.circle(frame, (int(kx), int(ky)), 4, (0,255,0), -1) 

# 4. Draw Edges

In [12]:
EDGES = {
    (0, 1): 'm',
    (0, 2): 'c',
    (1, 3): 'm',
    (2, 4): 'c',
    (0, 5): 'm',
    (0, 6): 'c',
    (5, 7): 'm',
    (7, 9): 'm',
    (6, 8): 'c',
    (8, 10): 'c',
    (5, 6): 'y',
    (5, 11): 'm',
    (6, 12): 'c',
    (11, 12): 'y',
    (11, 13): 'm',
    (13, 15): 'm',
    (12, 14): 'c',
    (14, 16): 'c'
}

In [13]:
def draw_connections(frame, keypoints, edges, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for edge, color in edges.items():
        p1, p2 = edge
        y1, x1, c1 = shaped[p1]
        y2, x2, c2 = shaped[p2]
        
        if (c1 > confidence_threshold) & (c2 > confidence_threshold):      
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0,0,255), 2)

In [14]:
mask.shape

NameError: name 'mask' is not defined